using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AtMega328pEmu.Emulator.Registers
{
	public static class IO
	{
		public const uint PINA = 0x20;
		public const uint DDRA = 0x21;
		public const uint PORTA = 0x22;
		public const uint PINB = 0x23;
		public const uint DDRB = 0x24;
		public const uint PORTB = 0x25;
		public const uint PINC = 0x26;
		public const uint DDRC = 0x27;
		public const uint PORTC = 0x28;
		public const uint PIND = 0x29;
		public const uint DDRD = 0x2A;
		public const uint PORTD = 0x2B;
		public const uint TIFR0 = 0x35;
		public const uint TIFR1 = 0x36;
		public const uint TIFR2 = 0x37;
		public const uint PCIFR = 0x3B;
		public const uint EIFR = 0x3C;
		public const uint EIMSK = 0x3D;
		public const uint GPIOR0 = 0x3E;
		public const uint EECR = 0x3F;
		public const uint EEDR = 0x40;
		public const uint EEARL = 0x41;
		public const uint EEARH = 0x42;
		public const uint GTCCR = 0x43;
		public const uint TCCR0A = 0x44;
		public const uint TCCR0B = 0x45;
		public const uint TCNT0 = 0x46;
		public const uint OCR0A = 0x47;
		public const uint OCR0B = 0x48;
		public const uint GPIOR1 = 0x4A;
		public const uint GPIOR2 = 0x4B;
		public const uint SPCR0 = 0x4C;
		public const uint SPSR0 = 0x4D;
		public const uint SPDR0 = 0x4E;
		public const uint ACSR = 0x50;
		public const uint DWDR = 0x51;
		public const uint SMCR = 0x53;
		public const uint MCUSR = 0x54;
		public const uint MCUCR = 0x55;
		public const uint SPMCSR = 0x57;
		public const uint SPL = 0x5D;
		public const uint SPH = 0x5E;
		public const uint SREG = 0x5F;
		public const uint WDTCSR = 0x60;
		public const uint CLKPR = 0x61;
		public const uint PRR = 0x64;
		public const uint OSCCAL = 0x66;
		public const uint PCICR = 0x68;
		public const uint EICRA = 0x69;
		public const uint PCMSK0 = 0x6B;
		public const uint PCMSK1 = 0x6C;
		public const uint PCMSK2 = 0x6D;
		public const uint TIMSK0 = 0x6E;
		public const uint TIMSK1 = 0x6F;
		public const uint TIMSK2 = 0x70;
		public const uint ADCL = 0x78;
		public const uint ADCH = 0x79;
		public const uint ADCSRA = 0x7A;
		public const uint ADCSRB = 0x7B;
		public const uint ADMUX = 0x7C;
		public const uint DIDR0 = 0x7E;
		public const uint DIDR1 = 0x7F;
		public const uint TCCR1A = 0x80;
		public const uint TCCR1B = 0x81;
		public const uint TCCR1C = 0x82;
		public const uint TCNT1L = 0x84;
		public const uint TCNT1H = 0x85;
		public const uint ICR1L = 0x86;
		public const uint ICR1H = 0x87;
		public const uint OCR1AL = 0x88;
		public const uint OCR1AH = 0x89;
		public const uint OCR1BL = 0x8A;
		public const uint OCR1BH = 0x8B;
		public const uint TCCR2A = 0xB0;
		public const uint TCCR2B = 0xB1;
		public const uint TCNT2 = 0xB2;
		public const uint OCR2A = 0xB3;
		public const uint OCR2B = 0xB4;
		public const uint ASSR = 0xB6;
		public const uint TWBR = 0xB8;
		public const uint TWSR = 0xB9;
		public const uint TWAR = 0xBA;
		public const uint TWDR = 0xBB;
		public const uint TWCR = 0xBC;
		public const uint TWAMR = 0xBD;
		public const uint UCSR0A = 0xC0;
		public const uint UCSR0B = 0xC1;
		public const uint UCSR0C = 0xC2;
		public const uint UBRR0L = 0xC4;
		public const uint UBRR0H = 0xC5;
		public const uint UDR0 = 0xC6;
	}
}
